### ISSUE TITLE
Problemas al instalar las librerias wsse y xmlsec

### ISSUE THREAD

**Issue by albermillan69** [odoocoop/odoo_pasarelas_de_pago#2]
Hola, estoy tratando de instalar el modulo en odoo 13 y python 3.7, pero tengo problemas al instalar las librerias wsse y xmlsec en python con windows 7. Dando el siguiente error:

C:\Users\Millan\AppData\Local\Programs\Python\Python37-32>pip install xmlsec
Collecting xmlsec
  Using cached xmlsec-1.3.3.tar.gz (29 kB)
Requirement already satisfied: pkgconfig in c:\users\millan\appdata\local\progra
ms\python\python37-32\lib\site-packages (from xmlsec) (1.5.1)
Requirement already satisfied: lxml>=3.0 in c:\users\millan\appdata\local\progra
ms\python\python37-32\lib\site-packages (from xmlsec) (4.5.0)
Building wheels for collected packages: xmlsec
  Building wheel for xmlsec (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\millan\appdata\local\programs\python\python37-32\python.ex
e' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Millan
\\AppData\\Local\\Temp\\pip-install-xv8wwg1j\\xmlsec\\setup.py'"'"'; __file__='"
'"'C:\\Users\\Millan\\AppData\\Local\\Temp\\pip-install-xv8wwg1j\\xmlsec\\setup.
py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replac
e('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec
'"'"'))' bdist_wheel -d 'C:\Users\Millan\AppData\Local\Temp\pip-wheel-7a_23xff'
       cwd: C:\Users\Millan\AppData\Local\Temp\pip-install-xv8wwg1j\xmlsec\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  error: HTTP Error 404: The specified blob does not exist.
  Retrieving "https://ci.appveyor.com/api/buildjobs/7k878q7rvogcdyd9/artifacts/l
ibxml2-2.9.4.win32.zip" to "build/extra\libxml2-2.9.4.win32.zip"
  ----------------------------------------
  ERROR: Failed building wheel for xmlsec
  Running setup.py clean for xmlsec
Failed to build xmlsec
Installing collected packages: xmlsec
    Running setup.py install for xmlsec ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\millan\appdata\local\programs\python\python37-32\python.
exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mill
an\\AppData\\Local\\Temp\\pip-install-xv8wwg1j\\xmlsec\\setup.py'"'"'; __file__=
'"'"'C:\\Users\\Millan\\AppData\\Local\\Temp\\pip-install-xv8wwg1j\\xmlsec\\setu
p.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().repl
ace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'ex
ec'"'"'))' install --record 'C:\Users\Millan\AppData\Local\Temp\pip-record-cr4k4
cfl\install-record.txt' --single-version-externally-managed --compile --install-
headers 'c:\users\millan\appdata\local\programs\python\python37-32\Include\xmlse
c'
         cwd: C:\Users\Millan\AppData\Local\Temp\pip-install-xv8wwg1j\xmlsec\

**Comment by dansanti** [comment]
hola!

1.- este repositorio está desactualizado
2.-no hay soporte para windows

**Comment by dansanti** [comment]
3.- No hay soporte para odoo 13 aún, estoy evaluando si lo haré

**Comment by dansanti** [comment]
se debe ir a https://gitlab.com/odoocoop/odoo_pasarelas_de_pago

**Comment by albermillan69** [comment]
Gracias por responder Daniel, pero deje a un lado la pasarela de webpay. Y
estoy con la de Khipu que tu creaste y se me esta presentando un problema.
Luego de realizar el pago del producto, el mismo permanece en el carrito,
no se confirma el pago por parte de odoo para seguir la gestión de la orden
de venta.

El módulo dice que esta completamente funcional y todas las transacciones
khipu odoo la reconoce como pendiente!

Que puede estar pasando?

**Comment by albermillan69** [comment]
Como comentario adicional, me llega un correo de khipu diciendo que falló
la notificación,  me arroja el link del servidor /payment/khipu/notify/(id)
no entiendo que puede estar pasando si luego de realizar el pago me dice
que se realiza exitosamente pero esta esperando confirmación

**Comment by dansanti** [comment]
estimado por favor comprender que por este medio todo código está desactualizado, todo desarrollo mío fue migrado a gitlab.com/dansanti o gitlab.com/odoocoop
